name: GitHub Actions Demo
on: [push, pull_request]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Verify `pom.xml` exists
        run: |
          if [ ! -f "./inventory.manager/pom.xml" ]; then
            echo "Error: pom.xml not found in inventory.manager directory.";
            exit 1;
          fi

      - name: Build and Test with Maven
        run: |
          mvn -f ./inventory.manager/pom.xml clean install
          mvn -f ./inventory.manager/pom.xml test
